name: gurps_modifiers
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Wilson, Marvin (jw9615) <email@example.com>

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.0
  quiver: ^2.1.2+1
  dart_utils:
    git:
      url: https://github.com/mjeffw/dart_utils

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  test_coverage: ^0.4.0
  build_runner: ^1.0.0
  json_serializable: ^3.2.3
